## data_loader.py
## This file just exists to separate out the data loading so I dont need to keep doing the read_csv part and makes the file more organised in terms of a pipeline
import pandas as pd
## since we did define data path in configuration.py, we can just import it to load our csv file into our python environment
from configuration import DATA_PATH
## load data method is self explanatory, it just reads the csv file and returns the dataframe generated by pandas
def load_data():
    df=pd.read_csv(DATA_PATH)
    return df